### ISSUE TITLE
CSS Klasse Skin in Body

### ISSUE THREAD

**Issue by ghost** [polarpixel/ppx_skin#1]
Der AgkSkin setzt eine Klasse in Body rein: https://github.com/redaxo/redaxo4/blob/master/redaxo/include/addons/be_style/plugins/agk_skin/config.inc.php#L34

Evtl. sollte das auch der PPX Skin machen. So kann man in Addons etc. auf den Skin reagieren direkt per CSS.

**Comment by polarpixel** [comment]
Ah, denkst Du, dass ein AddOn hier reagieren würde? Bisher dachte ich, ich als Theme-Ersteller müsste auf das AddOn reagieren. Aber gute Idee ...

**Comment by polarpixel** [comment]
Hab's eingebaut. Vielen Dank für die Anregung!

**Comment by ghost** [comment]
Cool :)
